# Generated by Django 5.2.16 on 2026-07-28 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_id', models.CharField(help_text='로봇 식별 ID', max_length=50)),
                ('file_name', models.CharField(help_text='파일명', max_length=255)),
                ('s3_key', models.CharField(help_text='S3 내부 저장 경로', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='업로드 일시')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='이름', max_length=100)),
                ('purpose', models.TextField(help_text='자료 사용 목적')),
                ('registered_at', models.DateTimeField(auto_now_add=True, help_text='가입 일시')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
