# Generated by Django 6.0.7 on 2026-07-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_id', models.CharField(max_length=50)),
                ('session_id', models.CharField(max_length=20)),
                ('schema_version', models.IntegerField(default=1)),
                ('data_version', models.IntegerField(default=1)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('uploaded_at', models.DateTimeField()),
                ('result', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE')], max_length=7)),
                ('duration_ms', models.BigIntegerField()),
                ('interface_commit', models.CharField(max_length=40)),
                ('time_sync', models.BooleanField()),
                ('content_digest', models.CharField(max_length=71)),
                ('status', models.CharField(choices=[('STAGING', 'STAGING'), ('READY', 'READY'), ('FAILED', 'FAILED')], default='STAGING', max_length=7)),
                ('row_counts', models.JSONField(default=dict)),
                ('file_sizes', models.JSONField(default=dict)),
                ('file_hashes', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-started_at', '-session_id'],
                'indexes': [models.Index(fields=['-started_at', '-session_id'], name='idx_session_listing'), models.Index(fields=['status'], name='idx_session_status')],
                'constraints': [models.UniqueConstraint(fields=('robot_id', 'session_id'), name='uq_session_robot_session')],
            },
        ),
    ]
