# Generated by Django 6.0.7 on 2026-07-30 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MotorLogFile',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
